# Generated by Django 5.2.3 on 2025-06-11 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_lat', models.FloatField(null=True)),
                ('player1_lon', models.FloatField(null=True)),
                ('player1_score', models.IntegerField(null=True)),
                ('player2_lat', models.FloatField(null=True)),
                ('player2_lon', models.FloatField(null=True)),
                ('player2_score', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.landmark')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_player2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
