# Generated by Django 5.2.3 on 2025-06-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_battle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='image',
            field=models.ImageField(upload_to='landmarks/'),
        ),
    ]
