# Generated by Django 5.2.1 on 2025-06-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_battle_player2_delete_matchmakingqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='hint_image',
            field=models.ImageField(blank=True, null=True, upload_to='hints/'),
        ),
    ]
